FROM node:18-alpine

WORKDIR /app

# Installer les dépendances en premier (cache Docker)
COPY package*.json ./
RUN npm install

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 5000

# Variables d'environnement
ENV NODE_ENV=development
ENV PORT=5000

CMD ["npm", "run", "dev"]